### ISSUE TITLE
Resolve BLAST dependency

### ISSUE THREAD

**Issue by hettling** [ropensci/phylotaR#4]
The code relies on blastn for the clustering. I'm not sure if this is acceptable for a CRAN (or bioconductor or similar) submission. 

This should be checked and if it is impossible to depend on an external tool, blastn should be included in the package.

As far as I know, all blast R packages do remote blasting, which is however not an option for this package.

**Comment by rvosa** [comment]
Maybe check with @rOpenSci to see how they deal with this?

**Comment by DomBennett** [comment]
CRAN, bioconductor and ropensci all seem to allow it.

This [R package](https://github.com/ropensci/magick) does image processing through external programs and is on CRAN and is part of ropensci. Looks like you just need to list external deps under 'SystemRequirements' in DESCRIPTION.
