### ISSUE TITLE
Unable to find correct versions of NCBI BLAST+ tools

### ISSUE THREAD

**Issue by EricaBarroso** [ropensci/phylotaR#40]
I am getting this error (last line):
> library(phylotaR)
> wd <- /apps/Acanthaceae
Error: unexpected '/' in "wd <- /"
> wd <- "/apps/Acanthaceae"
> ncbi_dr <- "/usr/lib/ncbi-blast+"
> txid <- 4185
> setup(wd = wd, txid = txid, ncbi_dr = ncbi_dr, v = TRUE)
-------------------------------------------------
phylotaR: Implementation of PhyLoTa in R [v1.0.0]
-------------------------------------------------
Checking for valid NCBI BLAST+ Tools ...
Failed to run: [/usr/lib/ncbi-blast+/makeblastdb]. Reason:
[Error : Failed to execute '/usr/lib/ncbi-blast+/makeblastdb' (No such file or directory)
]Failed to run: [/usr/lib/ncbi-blast+/blastn]. Reason:
[Error : Failed to execute '/usr/lib/ncbi-blast+/blastn' (No such file or directory)
]Error:Unable to find correct versions of NCBI BLAST+ tools
Error in blast_setup(d = ncbi_dr, v = v, wd = wd) : 
  Unable to find correct versions of NCBI BLAST+ tools

I think BLAST+ is ok in my computer. Perhaps I have to install some specific database?
If I type: 
sudo apt install ncbi-blast+
I get: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ncbi-blast+ is already the newest version (2.6.0-1).
0 upgraded, 0 newly installed, 0 to remove and 83 not upgraded.

**Comment by EricaBarroso** [comment]
I made those directories (makeblastdb and blastn) and the error changed:
> setup(wd = wd, txid = txid, ncbi_dr = ncbi_dr, v = TRUE)
-------------------------------------------------
phylotaR: Implementation of PhyLoTa in R [v1.0.0]
-------------------------------------------------
Checking for valid NCBI BLAST+ Tools ...
Failed to run: [/usr/share/ncbi/data/makeblastdb]. Reason:
[Error : Failed to execute '/usr/share/ncbi/data/makeblastdb' (Permission denied)
]Failed to run: [/usr/share/ncbi/data/blastn]. Reason:
[Error : Failed to execute '/usr/share/ncbi/data/blastn' (Permission denied)
]Error:Unable to find correct versions of NCBI BLAST+ tools
Error in blast_setup(d = ncbi_dr, v = v, wd = wd) : 
  Unable to find correct versions of NCBI BLAST+ tools

I changed the permissions on the folder with the command:
sudo chmod 777 ./
Still get the same error.

**Comment by EricaBarroso** [comment]
this was solved by placing wd folder inside blast folder.

**Comment by EricaBarroso** [comment]
this was solved by placing R and wd folder in the same folder as blast

**Comment by maelle** [comment]
For info, we're looking for a new maintainer / a new maintainer team for this package, see #57 and feel free to volunteer, we'd be happy to help.
