### ISSUE TITLE
Dependency 'treeman' has been archived:

### ISSUE THREAD

**Issue by jeroen** [ropensci/phylotaR#45]
https://cran.r-project.org/web/packages/phylotaR/index.html

**Comment by nylander** [comment]
Should of course be taken care of. Meanwhile, this seems to work (on R 3.4.4, Linux):

``` R
library(devtools)
devtools::install_github('dombennett/treeman')
devtools::install_github(repo='ropensci/phylotaR', build_vignettes=TRUE)
```

**Comment by jeroen** [comment]
This is still unavailable. I know you can make it work with `install_github`, however we cannot build binary packages for phylotaR if there are hard dependencies that are not in ropensci or cran.

Would it be an option to move `treeman` to suggests?

**Comment by DomBennett** [comment]
Hmmm... I think there's some core functionality that depends on `treeman`.

Currently, re-doubling my efforts to get `treeman` back on CRAN.
