### ISSUE TITLE
makeblastdb failing to run

### ISSUE THREAD

**Issue by mrubenss** [ropensci/phylotaR#46]
Hello,

I'm having trouble to run the pipeline due to an error in BLAST.

This is my code and, on the last line, the error.

```
> library(phylotaR)
> wd <- 'C:/bioinfo/NCBI/Serpentes'
> ncbi_dr <- 'C:/bioinfo/NCBI/blast-2.10.0+/bin'
> txid <- 8570
> setup(wd = wd, txid = txid, ncbi_dr = ncbi_dr, v = TRUE)
-------------------------------------------------
phylotaR: Implementation of PhyLoTa in R [v1.2.0]
-------------------------------------------------
Checking for valid NCBI BLAST+ Tools ...
Found: [C:/bioinfo/NCBI/blast-2.10.0+/bin/makeblastdb]
Found: [C:/bioinfo/NCBI/blast-2.10.0+/bin/blastn]
. . Running makeblastdb
Erro: makeblastdb failed to run. Check BLAST log files.
```

**Comment by mariosandovalmx** [comment]
Same problem here. Have you solved this error?

**Comment by maelle** [comment]
For info, we're looking for a new maintainer / a new maintainer team for this package, see #57 and feel free to volunteer, we'd be happy to help.

**Comment by ShixiangWang** [comment]
This is similar to https://github.com/ropensci/phylotaR/issues/39, it should work in the latest version. If not, please file a new issue.
