### ISSUE TITLE
you probably don't want to link to the http://phylota.net/ website anymore

### ISSUE THREAD

**Issue by sckott** [ropensci/phylotaR#47]
see http://phylota.net/

@DomBennett

**Comment by DomBennett** [comment]
😱

**Comment by rvosa** [comment]
I agree. The contents, albeit potentially useful, are simply out of scope for the present project. For historical purposes it might make sense to refer to the most recent relevant version of the website, which is this one: https://web.archive.org/web/20180421030419/http://phylota.net/
