### ISSUE TITLE
Can not install the package in windows 

### ISSUE THREAD

**Issue by FishyguyNeel** [ropensci/phylotaR#54]
When I tried to install it from the code it did not install. Instead show this
The downloaded binary packages are in
	C:\Users\Admin\AppData\Local\Temp\RtmpoLzhjF\downloaded_packages
   '0' is not recognized as an internal or external command,
   operable program or batch file.

**Comment by maelle** [comment]
For info, we're looking for a new maintainer / a new maintainer team for this package, see #57 and feel free to volunteer, we'd be happy to help.

**Comment by ShixiangWang** [comment]
This seems not a package specific installation problem.
