### ISSUE TITLE
New Maintainer Wanted

### ISSUE THREAD

**Issue by maelle** [ropensci/phylotaR#57]
If you're interested, please comment in the issue. 
For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by ShixiangWang** [comment]
I would like to be the maintainer. It seems the CRAN check is okay for all platforms, why is it dropped from CRAN?

**Comment by maelle** [comment]
Thank you @ShixiangWang, you were super fast! I've invited you to a GitHub team that has admin access to this repository.

I don't see an explanation for the CRAN archival, maybe it was at the request of the former maintainer? So it'd be worth re-submitting.

Out of curiosity, are you an user of this package? Thanks again!

**Comment by ShixiangWang** [comment]
@maelle :) I am not the user. I just read the newsletter from rOpenSci and found this out. I work in bioinformatics, and think this tool may be useful to peers, so it may be worth taking over this and seeing how I can help.

**Comment by ShixiangWang** [comment]
@maelle Thanks for your operation. I will try checking this package and modifying it, so it can be back on CRAN.

**Comment by maelle** [comment]
Thanks so much!

I've also sent you an invite to rOpenSci slack workspace (where you were not listed) as there's a package-maintenance channel there, but you can choose not to join. Feel free to ping me here or there if you have questions or problems!
