### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ShixiangWang** [ropensci/phylotaR#58]
- [x] The strong dependency https://github.com/ropensci/restez is not on CRAN. (This has been fixed in v2.0)
- [x] Windows check failed.

? 

- https://github.com/pachterlab/gget
- https://github.com/ropensci/phylotaR/issues/45

**Comment by maelle** [comment]
Reg restez, you might want to ask the new maintainer @joelnitta

**Comment by joelnitta** [comment]
Please see https://github.com/ropensci/restez/issues/26 for the current work-around and eventual long-term solution for {restez}. For now you need to install {MonetDBLite} and {restez} from GitHub using devtools or remotes.

**Comment by ShixiangWang** [comment]
@joelnitta Thanks, I have included the latest version of restez.

**Comment by joelnitta** [comment]
@ShixiangWang great! Just to clarify though, restez isn't on CRAN just yet. Although v2.0.0 now uses duckdb, there is now another issue (https://github.com/ropensci/restez/issues/33) that needs to get fixed before I can submit to CRAN. Sorry for the confusion.

**Comment by joelnitta** [comment]
@ShixiangWang FYI restez is now [on CRAN](https://cran.r-project.org/web/packages/restez/index.html), can be installed with `install.packages("restez")`

**Comment by ShixiangWang** [comment]
@joelnitta Thanks :)
