### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/phylotaR#61]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: outfmt_get
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
@ShixiangWang Friendly reminder :smile_cat:

**Comment by ShixiangWang** [comment]
@maelle Thanks for your notion. Sorry for the delay as I did not get the message before you at me. I will take a look and fix it in the two days :).

**Comment by maelle** [comment]
no problem, thank you!
