### ISSUE TITLE
No need for restez_connect()

### ISSUE THREAD

**Issue by joelnitta** [ropensci/phylotaR#62]
[As of restez v2.1.0](https://docs.ropensci.org/restez/news/index.html#new-features-2-1-0), there is no need for the user to call `restez_connect()`. Making unnecessary connections to the database can cause warnings or errors, so this should be avoided.

That means lines like this:

https://github.com/ropensci/phylotaR/blob/861fa662e3b97114de7758a825750c489dc13eb3/R/stage2.R#L24-L25

can (and should) be safely deleted.

**Comment by ShixiangWang** [comment]
@joelnitta Thanks :)
