### ISSUE TITLE
Fetch and error seem to be stuck

### ISSUE THREAD

**Issue by jamie-thompson** [ropensci/phylotaR#68]
What does this mean?  Has it stopped running?

`Retrying in [300s] for [fetch]
Retrying in [300s] for [fetch]
Retrying in [300s] for [fetch]
Retrying in [300s] for [fetch]
`

```
Retrying in [1s] for [search]
Retrying in [3s] for [search]
Retrying in [6s] for [search]
Retrying in [10s] for [search]
Retrying in [60s] for [search]
Retrying in [300s] for [search]
Retrying in [300s] for [search]
```

**Comment by ShixiangWang** [comment]
@jamie-thompson  Could you provide a minimal reproducible example for debugging purposes?

**Comment by ShixiangWang** [comment]
This is typically an internet issue. Please show your code that can reproduce the error.
