### ISSUE TITLE
Problem running makeblastdb

### ISSUE THREAD

**Issue by GRyan-geophy** [ropensci/phylotaR#73]
Hi, 

I am having an issue with error below. I have installed BLAST+ using the windows 64 executable but when I try and run in R I get the repeated error makeblastdb failed to run. I have checked the file versions and they are all above 2. Any help would be appreciated. 

wd <- "C:/Users/user/onedrive/Documents/Crocus"
> ncbi_dr <- "C:/Program Files/NCBI/blast-2.16.0+/bin/"
> txid <- 58949
> setup(wd = wd, txid = txid, ncbi_dr = ncbi_dr, v = TRUE)

-------------------------------------------------
phylotaR: Implementation of PhyLoTa in R [v1.3.0]
-------------------------------------------------
Checking for valid NCBI BLAST+ Tools ...
Found: [C:\Program Files\NCBI\blast-2.16.0+\bin/makeblastdb]
Found: [C:\Program Files\NCBI\blast-2.16.0+\bin/blastn]
. . Running makeblastdb
Error: makeblastdb failed to run. Check BLAST log files.

In testdbfl file: 
BLAST options error: Please provide a database name using -out

**Comment by ShixiangWang** [comment]
@GRyan-geophy Hi, thanks for reporting this to us. 

1. The package was tested with blast-2.14.0 (<https://github.com/ropensci/phylotaR/blob/master/justfile>), could you re-run with this version? 
2. And if not fix, if possible, could you reproduce this in Linux system as I have no windows to check this possible bug related to blast.

**Comment by GRyan-geophy** [comment]
Hi Shixiang, 

I have run it using blast-2.14.0 but it has made no difference. I am wondering whether there is something intrinsic within my computer because I ran it on a different computer and it worked. Sadly I do not have access to a linux system. 

Many Thanks, 
George

**Comment by ShixiangWang** [comment]
Did you mean it works on another windows? Ohh, that means your computer may be not compatible with the blast software, maybe you need to test older versions of blast one by one.
